// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: color.sql

package db

import (
	"context"
	"database/sql"
)

const createColor = `-- name: CreateColor :one
INSERT INTO colors (
  store_id, store_name, name, value
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, store_id, store_name, name, value, created_at, updated_at
`

type CreateColorParams struct {
	StoreID   int64  `db:"store_id" json:"store_id"`
	StoreName string `db:"store_name" json:"store_name"`
	Name      string `db:"name" json:"name"`
	Value     string `db:"value" json:"value"`
}

func (q *Queries) CreateColor(ctx context.Context, arg CreateColorParams) (Color, error) {
	row := q.db.QueryRowContext(ctx, createColor,
		arg.StoreID,
		arg.StoreName,
		arg.Name,
		arg.Value,
	)
	var i Color
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.StoreName,
		&i.Name,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteColor = `-- name: DeleteColor :exec
DELETE FROM colors
WHERE id = $1
`

func (q *Queries) DeleteColor(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteColor, id)
	return err
}

const getColor = `-- name: GetColor :one
SELECT id, store_id, store_name, name, value, created_at, updated_at FROM colors
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetColor(ctx context.Context, id int64) (Color, error) {
	row := q.db.QueryRowContext(ctx, getColor, id)
	var i Color
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.StoreName,
		&i.Name,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getColors = `-- name: GetColors :many
SELECT id, store_id, store_name, name, value, created_at, updated_at FROM colors
WHERE store_id = $1
ORDER BY id
`

func (q *Queries) GetColors(ctx context.Context, storeID int64) ([]Color, error) {
	rows, err := q.db.QueryContext(ctx, getColors, storeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Color{}
	for rows.Next() {
		var i Color
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.StoreName,
			&i.Name,
			&i.Value,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateColor = `-- name: UpdateColor :exec
UPDATE colors
SET
  name = COALESCE($1, name),
  value = COALESCE($2, value)
WHERE 
  id = $3
  AND store_id = $4
`

type UpdateColorParams struct {
	Name    sql.NullString `db:"name" json:"name"`
	Value   sql.NullString `db:"value" json:"value"`
	ID      int64          `db:"id" json:"id"`
	StoreID int64          `db:"store_id" json:"store_id"`
}

func (q *Queries) UpdateColor(ctx context.Context, arg UpdateColorParams) error {
	_, err := q.db.ExecContext(ctx, updateColor,
		arg.Name,
		arg.Value,
		arg.ID,
		arg.StoreID,
	)
	return err
}
