// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	CreateBillboard(ctx context.Context, arg CreateBillboardParams) (Billboard, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateStore(ctx context.Context, name string) (Store, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteBillboard(ctx context.Context, id int64) error
	DeleteStore(ctx context.Context, id int64) error
	GetBillboard(ctx context.Context, id int64) (Billboard, error)
	GetBillboards(ctx context.Context, storeID int64) ([]Billboard, error)
	GetFirstStore(ctx context.Context) (Store, error)
	GetStore(ctx context.Context, id int64) (Store, error)
	GetStores(ctx context.Context) ([]Store, error)
	GetUser(ctx context.Context, email string) (User, error)
	Logout(ctx context.Context, arg LogoutParams) error
	UpdateBillboard(ctx context.Context, arg UpdateBillboardParams) error
	UpdateStore(ctx context.Context, arg UpdateStoreParams) error
}

var _ Querier = (*Queries)(nil)
