// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	CreateBillboard(ctx context.Context, arg CreateBillboardParams) (Billboard, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateColor(ctx context.Context, arg CreateColorParams) (Color, error)
	CreateOrder(ctx context.Context, storeID int64) (Order, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateProductCategory(ctx context.Context, arg CreateProductCategoryParams) (ProductCategory, error)
	CreateProductColor(ctx context.Context, arg CreateProductColorParams) (ProductColor, error)
	CreateProductSize(ctx context.Context, arg CreateProductSizeParams) (ProductSize, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateSize(ctx context.Context, arg CreateSizeParams) (Size, error)
	CreateStore(ctx context.Context, name string) (Store, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteBillboard(ctx context.Context, id int64) error
	DeleteCategory(ctx context.Context, id int64) error
	DeleteColor(ctx context.Context, id int64) error
	DeleteProduct(ctx context.Context, id int64) error
	DeleteProductCategory(ctx context.Context, productID int64) error
	DeleteProductColor(ctx context.Context, productID int64) error
	DeleteProductSize(ctx context.Context, productID int64) error
	DeleteSession(ctx context.Context) error
	DeleteSize(ctx context.Context, id int64) error
	DeleteStore(ctx context.Context, id int64) error
	GetBillboard(ctx context.Context, id int64) (Billboard, error)
	GetBillboards(ctx context.Context, storeID int64) ([]Billboard, error)
	GetCategories(ctx context.Context, storeID int64) ([]GetCategoriesRow, error)
	GetCategory(ctx context.Context, id int64) (GetCategoryRow, error)
	GetColor(ctx context.Context, id int64) (Color, error)
	GetColors(ctx context.Context, storeID int64) ([]Color, error)
	GetFirstStore(ctx context.Context) (GetFirstStoreRow, error)
	GetOrders(ctx context.Context, storeID int64) ([]Order, error)
	GetProduct(ctx context.Context, arg GetProductParams) (GetProductRow, error)
	GetProducts(ctx context.Context, storeID int64) ([]GetProductsRow, error)
	GetSize(ctx context.Context, id int64) (Size, error)
	GetSizes(ctx context.Context, storeID int64) ([]Size, error)
	GetStore(ctx context.Context, id int64) (GetStoreRow, error)
	GetStores(ctx context.Context, limit int32) ([]GetStoresRow, error)
	GetUser(ctx context.Context, email string) (User, error)
	Logout(ctx context.Context, arg LogoutParams) error
	UpdateBillboard(ctx context.Context, arg UpdateBillboardParams) error
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) error
	UpdateColor(ctx context.Context, arg UpdateColorParams) error
	UpdateProduct(ctx context.Context, arg UpdateProductParams) error
	UpdateProductCategory(ctx context.Context, arg UpdateProductCategoryParams) error
	UpdateProductColor(ctx context.Context, arg UpdateProductColorParams) error
	UpdateProductSize(ctx context.Context, arg UpdateProductSizeParams) error
	UpdateSize(ctx context.Context, arg UpdateSizeParams) error
	UpdateStore(ctx context.Context, arg UpdateStoreParams) error
}

var _ Querier = (*Queries)(nil)
