// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: store.sql

package db

import (
	"context"
)

const createStore = `-- name: CreateStore :one
INSERT INTO stores (
    name
) VALUES (
  $1
)
RETURNING id, name, created_at
`

func (q *Queries) CreateStore(ctx context.Context, name string) (Store, error) {
	row := q.db.QueryRowContext(ctx, createStore, name)
	var i Store
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}
