// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.29.2
// source: rpc_color.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateColorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StoreId string `protobuf:"bytes,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Value   string `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *CreateColorRequest) Reset() {
	*x = CreateColorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_color_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateColorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateColorRequest) ProtoMessage() {}

func (x *CreateColorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_color_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateColorRequest.ProtoReflect.Descriptor instead.
func (*CreateColorRequest) Descriptor() ([]byte, []int) {
	return file_rpc_color_proto_rawDescGZIP(), []int{0}
}

func (x *CreateColorRequest) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

func (x *CreateColorRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateColorRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type CreateColorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Color *Color `protobuf:"bytes,1,opt,name=color,proto3" json:"color,omitempty"`
}

func (x *CreateColorResponse) Reset() {
	*x = CreateColorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_color_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateColorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateColorResponse) ProtoMessage() {}

func (x *CreateColorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_color_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateColorResponse.ProtoReflect.Descriptor instead.
func (*CreateColorResponse) Descriptor() ([]byte, []int) {
	return file_rpc_color_proto_rawDescGZIP(), []int{1}
}

func (x *CreateColorResponse) GetColor() *Color {
	if x != nil {
		return x.Color
	}
	return nil
}

type GetColorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetColorRequest) Reset() {
	*x = GetColorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_color_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetColorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetColorRequest) ProtoMessage() {}

func (x *GetColorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_color_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetColorRequest.ProtoReflect.Descriptor instead.
func (*GetColorRequest) Descriptor() ([]byte, []int) {
	return file_rpc_color_proto_rawDescGZIP(), []int{2}
}

func (x *GetColorRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetColorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Color *Color `protobuf:"bytes,1,opt,name=color,proto3" json:"color,omitempty"`
}

func (x *GetColorResponse) Reset() {
	*x = GetColorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_color_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetColorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetColorResponse) ProtoMessage() {}

func (x *GetColorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_color_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetColorResponse.ProtoReflect.Descriptor instead.
func (*GetColorResponse) Descriptor() ([]byte, []int) {
	return file_rpc_color_proto_rawDescGZIP(), []int{3}
}

func (x *GetColorResponse) GetColor() *Color {
	if x != nil {
		return x.Color
	}
	return nil
}

type GetColorsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StoreId string `protobuf:"bytes,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
}

func (x *GetColorsRequest) Reset() {
	*x = GetColorsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_color_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetColorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetColorsRequest) ProtoMessage() {}

func (x *GetColorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_color_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetColorsRequest.ProtoReflect.Descriptor instead.
func (*GetColorsRequest) Descriptor() ([]byte, []int) {
	return file_rpc_color_proto_rawDescGZIP(), []int{4}
}

func (x *GetColorsRequest) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

type GetColorsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Colors []*Color `protobuf:"bytes,1,rep,name=colors,proto3" json:"colors,omitempty"`
}

func (x *GetColorsResponse) Reset() {
	*x = GetColorsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_color_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetColorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetColorsResponse) ProtoMessage() {}

func (x *GetColorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_color_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetColorsResponse.ProtoReflect.Descriptor instead.
func (*GetColorsResponse) Descriptor() ([]byte, []int) {
	return file_rpc_color_proto_rawDescGZIP(), []int{5}
}

func (x *GetColorsResponse) GetColors() []*Color {
	if x != nil {
		return x.Colors
	}
	return nil
}

type UpdateColorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Value string `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *UpdateColorRequest) Reset() {
	*x = UpdateColorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_color_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateColorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateColorRequest) ProtoMessage() {}

func (x *UpdateColorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_color_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateColorRequest.ProtoReflect.Descriptor instead.
func (*UpdateColorRequest) Descriptor() ([]byte, []int) {
	return file_rpc_color_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateColorRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateColorRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateColorRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type UpdateColorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *UpdateColorResponse) Reset() {
	*x = UpdateColorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_color_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateColorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateColorResponse) ProtoMessage() {}

func (x *UpdateColorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_color_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateColorResponse.ProtoReflect.Descriptor instead.
func (*UpdateColorResponse) Descriptor() ([]byte, []int) {
	return file_rpc_color_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateColorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteColorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteColorRequest) Reset() {
	*x = DeleteColorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_color_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteColorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteColorRequest) ProtoMessage() {}

func (x *DeleteColorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_color_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteColorRequest.ProtoReflect.Descriptor instead.
func (*DeleteColorRequest) Descriptor() ([]byte, []int) {
	return file_rpc_color_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteColorRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteColorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *DeleteColorResponse) Reset() {
	*x = DeleteColorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_color_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteColorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteColorResponse) ProtoMessage() {}

func (x *DeleteColorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_color_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteColorResponse.ProtoReflect.Descriptor instead.
func (*DeleteColorResponse) Descriptor() ([]byte, []int) {
	return file_rpc_color_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteColorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_rpc_color_proto protoreflect.FileDescriptor

var file_rpc_color_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x72, 0x70, 0x63, 0x5f, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x0d, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x59, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f,
	0x6c, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x74,
	0x6f, 0x72, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x74,
	0x6f, 0x72, 0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22,
	0x36, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6f, 0x6c, 0x6f, 0x72,
	0x52, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x22, 0x21, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x43, 0x6f,
	0x6c, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x33, 0x0a, 0x10, 0x47, 0x65,
	0x74, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f,
	0x0a, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e,
	0x70, 0x62, 0x2e, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x52, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x22,
	0x2d, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x49, 0x64, 0x22, 0x36,
	0x0a, 0x11, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x06, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x52, 0x06,
	0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x73, 0x22, 0x4e, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x2f, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x24, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2f, 0x0a,
	0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x2e,
	0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x65, 0x62, 0x75,
	0x6b, 0x61, 0x63, 0x6f, 0x64, 0x65, 0x73, 0x32, 0x31, 0x2f, 0x73, 0x6f, 0x6c, 0x65, 0x6c, 0x75,
	0x78, 0x75, 0x72, 0x79, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_color_proto_rawDescOnce sync.Once
	file_rpc_color_proto_rawDescData = file_rpc_color_proto_rawDesc
)

func file_rpc_color_proto_rawDescGZIP() []byte {
	file_rpc_color_proto_rawDescOnce.Do(func() {
		file_rpc_color_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_color_proto_rawDescData)
	})
	return file_rpc_color_proto_rawDescData
}

var file_rpc_color_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_rpc_color_proto_goTypes = []interface{}{
	(*CreateColorRequest)(nil),  // 0: pb.CreateColorRequest
	(*CreateColorResponse)(nil), // 1: pb.CreateColorResponse
	(*GetColorRequest)(nil),     // 2: pb.GetColorRequest
	(*GetColorResponse)(nil),    // 3: pb.GetColorResponse
	(*GetColorsRequest)(nil),    // 4: pb.GetColorsRequest
	(*GetColorsResponse)(nil),   // 5: pb.GetColorsResponse
	(*UpdateColorRequest)(nil),  // 6: pb.UpdateColorRequest
	(*UpdateColorResponse)(nil), // 7: pb.UpdateColorResponse
	(*DeleteColorRequest)(nil),  // 8: pb.DeleteColorRequest
	(*DeleteColorResponse)(nil), // 9: pb.DeleteColorResponse
	(*Color)(nil),               // 10: pb.Color
}
var file_rpc_color_proto_depIdxs = []int32{
	10, // 0: pb.CreateColorResponse.color:type_name -> pb.Color
	10, // 1: pb.GetColorResponse.color:type_name -> pb.Color
	10, // 2: pb.GetColorsResponse.colors:type_name -> pb.Color
	3,  // [3:3] is the sub-list for method output_type
	3,  // [3:3] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_rpc_color_proto_init() }
func file_rpc_color_proto_init() {
	if File_rpc_color_proto != nil {
		return
	}
	file_general_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_rpc_color_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateColorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_color_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateColorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_color_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetColorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_color_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetColorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_color_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetColorsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_color_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetColorsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_color_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateColorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_color_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateColorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_color_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteColorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_color_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteColorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_color_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_color_proto_goTypes,
		DependencyIndexes: file_rpc_color_proto_depIdxs,
		MessageInfos:      file_rpc_color_proto_msgTypes,
	}.Build()
	File_rpc_color_proto = out.File
	file_rpc_color_proto_rawDesc = nil
	file_rpc_color_proto_goTypes = nil
	file_rpc_color_proto_depIdxs = nil
}
