// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.29.2
// source: rpc_billboard.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateBillboardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StoreId  string `protobuf:"bytes,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	Label    string `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	ImageUrl string `protobuf:"bytes,3,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
}

func (x *CreateBillboardRequest) Reset() {
	*x = CreateBillboardRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_billboard_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBillboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBillboardRequest) ProtoMessage() {}

func (x *CreateBillboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_billboard_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBillboardRequest.ProtoReflect.Descriptor instead.
func (*CreateBillboardRequest) Descriptor() ([]byte, []int) {
	return file_rpc_billboard_proto_rawDescGZIP(), []int{0}
}

func (x *CreateBillboardRequest) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

func (x *CreateBillboardRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *CreateBillboardRequest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

type CreateBillboardResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Billboard *Billboard `protobuf:"bytes,1,opt,name=billboard,proto3" json:"billboard,omitempty"`
}

func (x *CreateBillboardResponse) Reset() {
	*x = CreateBillboardResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_billboard_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBillboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBillboardResponse) ProtoMessage() {}

func (x *CreateBillboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_billboard_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBillboardResponse.ProtoReflect.Descriptor instead.
func (*CreateBillboardResponse) Descriptor() ([]byte, []int) {
	return file_rpc_billboard_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBillboardResponse) GetBillboard() *Billboard {
	if x != nil {
		return x.Billboard
	}
	return nil
}

type GetBillboardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetBillboardRequest) Reset() {
	*x = GetBillboardRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_billboard_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBillboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBillboardRequest) ProtoMessage() {}

func (x *GetBillboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_billboard_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBillboardRequest.ProtoReflect.Descriptor instead.
func (*GetBillboardRequest) Descriptor() ([]byte, []int) {
	return file_rpc_billboard_proto_rawDescGZIP(), []int{2}
}

func (x *GetBillboardRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetBillboardResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Billboard *Billboard `protobuf:"bytes,1,opt,name=billboard,proto3" json:"billboard,omitempty"`
}

func (x *GetBillboardResponse) Reset() {
	*x = GetBillboardResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_billboard_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBillboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBillboardResponse) ProtoMessage() {}

func (x *GetBillboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_billboard_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBillboardResponse.ProtoReflect.Descriptor instead.
func (*GetBillboardResponse) Descriptor() ([]byte, []int) {
	return file_rpc_billboard_proto_rawDescGZIP(), []int{3}
}

func (x *GetBillboardResponse) GetBillboard() *Billboard {
	if x != nil {
		return x.Billboard
	}
	return nil
}

type GetBillboardsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StoreId string `protobuf:"bytes,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
}

func (x *GetBillboardsRequest) Reset() {
	*x = GetBillboardsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_billboard_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBillboardsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBillboardsRequest) ProtoMessage() {}

func (x *GetBillboardsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_billboard_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBillboardsRequest.ProtoReflect.Descriptor instead.
func (*GetBillboardsRequest) Descriptor() ([]byte, []int) {
	return file_rpc_billboard_proto_rawDescGZIP(), []int{4}
}

func (x *GetBillboardsRequest) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

type GetBillboardsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Billboards []*Billboard `protobuf:"bytes,1,rep,name=billboards,proto3" json:"billboards,omitempty"`
}

func (x *GetBillboardsResponse) Reset() {
	*x = GetBillboardsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_billboard_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBillboardsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBillboardsResponse) ProtoMessage() {}

func (x *GetBillboardsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_billboard_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBillboardsResponse.ProtoReflect.Descriptor instead.
func (*GetBillboardsResponse) Descriptor() ([]byte, []int) {
	return file_rpc_billboard_proto_rawDescGZIP(), []int{5}
}

func (x *GetBillboardsResponse) GetBillboards() []*Billboard {
	if x != nil {
		return x.Billboards
	}
	return nil
}

type UpdateBillboardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Label    string `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	ImageUrl string `protobuf:"bytes,3,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
}

func (x *UpdateBillboardRequest) Reset() {
	*x = UpdateBillboardRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_billboard_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateBillboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBillboardRequest) ProtoMessage() {}

func (x *UpdateBillboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_billboard_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBillboardRequest.ProtoReflect.Descriptor instead.
func (*UpdateBillboardRequest) Descriptor() ([]byte, []int) {
	return file_rpc_billboard_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateBillboardRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateBillboardRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *UpdateBillboardRequest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

type UpdateBillboardResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *UpdateBillboardResponse) Reset() {
	*x = UpdateBillboardResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_billboard_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateBillboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBillboardResponse) ProtoMessage() {}

func (x *UpdateBillboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_billboard_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBillboardResponse.ProtoReflect.Descriptor instead.
func (*UpdateBillboardResponse) Descriptor() ([]byte, []int) {
	return file_rpc_billboard_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateBillboardResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteBillboardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteBillboardRequest) Reset() {
	*x = DeleteBillboardRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_billboard_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBillboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBillboardRequest) ProtoMessage() {}

func (x *DeleteBillboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_billboard_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBillboardRequest.ProtoReflect.Descriptor instead.
func (*DeleteBillboardRequest) Descriptor() ([]byte, []int) {
	return file_rpc_billboard_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteBillboardRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteBillboardResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *DeleteBillboardResponse) Reset() {
	*x = DeleteBillboardResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_billboard_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBillboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBillboardResponse) ProtoMessage() {}

func (x *DeleteBillboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_billboard_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBillboardResponse.ProtoReflect.Descriptor instead.
func (*DeleteBillboardResponse) Descriptor() ([]byte, []int) {
	return file_rpc_billboard_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteBillboardResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_rpc_billboard_proto protoreflect.FileDescriptor

var file_rpc_billboard_proto_rawDesc = []byte{
	0x0a, 0x13, 0x72, 0x70, 0x63, 0x5f, 0x62, 0x69, 0x6c, 0x6c, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x0d, 0x67, 0x65, 0x6e, 0x65, 0x72,
	0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x66, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x42, 0x69, 0x6c, 0x6c, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x49, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x61,
	0x62, 0x65, 0x6c, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x75, 0x72, 0x6c,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c,
	0x22, 0x46, 0x0a, 0x17, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x69, 0x6c, 0x6c, 0x62, 0x6f,
	0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x09, 0x62,
	0x69, 0x6c, 0x6c, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x70, 0x62, 0x2e, 0x42, 0x69, 0x6c, 0x6c, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x52, 0x09, 0x62,
	0x69, 0x6c, 0x6c, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x22, 0x25, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x42,
	0x69, 0x6c, 0x6c, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x43, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x42, 0x69, 0x6c, 0x6c, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x09, 0x62, 0x69, 0x6c, 0x6c, 0x62,
	0x6f, 0x61, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e,
	0x42, 0x69, 0x6c, 0x6c, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x52, 0x09, 0x62, 0x69, 0x6c, 0x6c, 0x62,
	0x6f, 0x61, 0x72, 0x64, 0x22, 0x31, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x42, 0x69, 0x6c, 0x6c, 0x62,
	0x6f, 0x61, 0x72, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08,
	0x73, 0x74, 0x6f, 0x72, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x73, 0x74, 0x6f, 0x72, 0x65, 0x49, 0x64, 0x22, 0x46, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x42, 0x69,
	0x6c, 0x6c, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x2d, 0x0a, 0x0a, 0x62, 0x69, 0x6c, 0x6c, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x69, 0x6c, 0x6c, 0x62, 0x6f,
	0x61, 0x72, 0x64, 0x52, 0x0a, 0x62, 0x69, 0x6c, 0x6c, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x73, 0x22,
	0x5b, 0x0a, 0x16, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x69, 0x6c, 0x6c, 0x62, 0x6f, 0x61,
	0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x62,
	0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x12,
	0x1b, 0x0a, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x22, 0x33, 0x0a, 0x17,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x69, 0x6c, 0x6c, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x22, 0x28, 0x0a, 0x16, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x69, 0x6c, 0x6c, 0x62,
	0x6f, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x33, 0x0a, 0x17, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x69, 0x6c, 0x6c, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x42, 0x2e, 0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x65,
	0x62, 0x75, 0x6b, 0x61, 0x63, 0x6f, 0x64, 0x65, 0x73, 0x32, 0x31, 0x2f, 0x73, 0x6f, 0x6c, 0x65,
	0x6c, 0x75, 0x78, 0x75, 0x72, 0x79, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_billboard_proto_rawDescOnce sync.Once
	file_rpc_billboard_proto_rawDescData = file_rpc_billboard_proto_rawDesc
)

func file_rpc_billboard_proto_rawDescGZIP() []byte {
	file_rpc_billboard_proto_rawDescOnce.Do(func() {
		file_rpc_billboard_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_billboard_proto_rawDescData)
	})
	return file_rpc_billboard_proto_rawDescData
}

var file_rpc_billboard_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_rpc_billboard_proto_goTypes = []interface{}{
	(*CreateBillboardRequest)(nil),  // 0: pb.CreateBillboardRequest
	(*CreateBillboardResponse)(nil), // 1: pb.CreateBillboardResponse
	(*GetBillboardRequest)(nil),     // 2: pb.GetBillboardRequest
	(*GetBillboardResponse)(nil),    // 3: pb.GetBillboardResponse
	(*GetBillboardsRequest)(nil),    // 4: pb.GetBillboardsRequest
	(*GetBillboardsResponse)(nil),   // 5: pb.GetBillboardsResponse
	(*UpdateBillboardRequest)(nil),  // 6: pb.UpdateBillboardRequest
	(*UpdateBillboardResponse)(nil), // 7: pb.UpdateBillboardResponse
	(*DeleteBillboardRequest)(nil),  // 8: pb.DeleteBillboardRequest
	(*DeleteBillboardResponse)(nil), // 9: pb.DeleteBillboardResponse
	(*Billboard)(nil),               // 10: pb.Billboard
}
var file_rpc_billboard_proto_depIdxs = []int32{
	10, // 0: pb.CreateBillboardResponse.billboard:type_name -> pb.Billboard
	10, // 1: pb.GetBillboardResponse.billboard:type_name -> pb.Billboard
	10, // 2: pb.GetBillboardsResponse.billboards:type_name -> pb.Billboard
	3,  // [3:3] is the sub-list for method output_type
	3,  // [3:3] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_rpc_billboard_proto_init() }
func file_rpc_billboard_proto_init() {
	if File_rpc_billboard_proto != nil {
		return
	}
	file_general_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_rpc_billboard_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBillboardRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_billboard_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBillboardResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_billboard_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBillboardRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_billboard_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBillboardResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_billboard_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBillboardsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_billboard_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBillboardsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_billboard_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateBillboardRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_billboard_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateBillboardResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_billboard_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteBillboardRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_billboard_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteBillboardResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_billboard_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_billboard_proto_goTypes,
		DependencyIndexes: file_rpc_billboard_proto_depIdxs,
		MessageInfos:      file_rpc_billboard_proto_msgTypes,
	}.Build()
	File_rpc_billboard_proto = out.File
	file_rpc_billboard_proto_rawDesc = nil
	file_rpc_billboard_proto_goTypes = nil
	file_rpc_billboard_proto_depIdxs = nil
}
