// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.29.2
// source: rpc_get_billboard.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBillboardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetBillboardRequest) Reset() {
	*x = GetBillboardRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_get_billboard_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBillboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBillboardRequest) ProtoMessage() {}

func (x *GetBillboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_get_billboard_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBillboardRequest.ProtoReflect.Descriptor instead.
func (*GetBillboardRequest) Descriptor() ([]byte, []int) {
	return file_rpc_get_billboard_proto_rawDescGZIP(), []int{0}
}

func (x *GetBillboardRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetBillboardResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Billboard *Billboard `protobuf:"bytes,1,opt,name=billboard,proto3" json:"billboard,omitempty"`
}

func (x *GetBillboardResponse) Reset() {
	*x = GetBillboardResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_get_billboard_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBillboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBillboardResponse) ProtoMessage() {}

func (x *GetBillboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_get_billboard_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBillboardResponse.ProtoReflect.Descriptor instead.
func (*GetBillboardResponse) Descriptor() ([]byte, []int) {
	return file_rpc_get_billboard_proto_rawDescGZIP(), []int{1}
}

func (x *GetBillboardResponse) GetBillboard() *Billboard {
	if x != nil {
		return x.Billboard
	}
	return nil
}

type GetBillboardsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StoreId int64 `protobuf:"varint,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
}

func (x *GetBillboardsRequest) Reset() {
	*x = GetBillboardsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_get_billboard_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBillboardsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBillboardsRequest) ProtoMessage() {}

func (x *GetBillboardsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_get_billboard_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBillboardsRequest.ProtoReflect.Descriptor instead.
func (*GetBillboardsRequest) Descriptor() ([]byte, []int) {
	return file_rpc_get_billboard_proto_rawDescGZIP(), []int{2}
}

func (x *GetBillboardsRequest) GetStoreId() int64 {
	if x != nil {
		return x.StoreId
	}
	return 0
}

type GetBillboardsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Billboards []*Billboard `protobuf:"bytes,1,rep,name=billboards,proto3" json:"billboards,omitempty"`
}

func (x *GetBillboardsResponse) Reset() {
	*x = GetBillboardsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_get_billboard_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBillboardsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBillboardsResponse) ProtoMessage() {}

func (x *GetBillboardsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_get_billboard_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBillboardsResponse.ProtoReflect.Descriptor instead.
func (*GetBillboardsResponse) Descriptor() ([]byte, []int) {
	return file_rpc_get_billboard_proto_rawDescGZIP(), []int{3}
}

func (x *GetBillboardsResponse) GetBillboards() []*Billboard {
	if x != nil {
		return x.Billboards
	}
	return nil
}

var File_rpc_get_billboard_proto protoreflect.FileDescriptor

var file_rpc_get_billboard_proto_rawDesc = []byte{
	0x0a, 0x17, 0x72, 0x70, 0x63, 0x5f, 0x67, 0x65, 0x74, 0x5f, 0x62, 0x69, 0x6c, 0x6c, 0x62, 0x6f,
	0x61, 0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x0f, 0x62,
	0x69, 0x6c, 0x6c, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x25,
	0x0a, 0x13, 0x47, 0x65, 0x74, 0x42, 0x69, 0x6c, 0x6c, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x43, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x42, 0x69, 0x6c, 0x6c,
	0x62, 0x6f, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a,
	0x09, 0x62, 0x69, 0x6c, 0x6c, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x69, 0x6c, 0x6c, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x52,
	0x09, 0x62, 0x69, 0x6c, 0x6c, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x22, 0x31, 0x0a, 0x14, 0x47, 0x65,
	0x74, 0x42, 0x69, 0x6c, 0x6c, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x49, 0x64, 0x22, 0x46, 0x0a,
	0x15, 0x47, 0x65, 0x74, 0x42, 0x69, 0x6c, 0x6c, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x0a, 0x62, 0x69, 0x6c, 0x6c, 0x62, 0x6f,
	0x61, 0x72, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e,
	0x42, 0x69, 0x6c, 0x6c, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x52, 0x0a, 0x62, 0x69, 0x6c, 0x6c, 0x62,
	0x6f, 0x61, 0x72, 0x64, 0x73, 0x42, 0x2e, 0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x65, 0x62, 0x75, 0x6b, 0x61, 0x63, 0x6f, 0x64, 0x65, 0x73, 0x32, 0x31,
	0x2f, 0x73, 0x6f, 0x6c, 0x65, 0x6c, 0x75, 0x78, 0x75, 0x72, 0x79, 0x2d, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_get_billboard_proto_rawDescOnce sync.Once
	file_rpc_get_billboard_proto_rawDescData = file_rpc_get_billboard_proto_rawDesc
)

func file_rpc_get_billboard_proto_rawDescGZIP() []byte {
	file_rpc_get_billboard_proto_rawDescOnce.Do(func() {
		file_rpc_get_billboard_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_get_billboard_proto_rawDescData)
	})
	return file_rpc_get_billboard_proto_rawDescData
}

var file_rpc_get_billboard_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_rpc_get_billboard_proto_goTypes = []interface{}{
	(*GetBillboardRequest)(nil),   // 0: pb.GetBillboardRequest
	(*GetBillboardResponse)(nil),  // 1: pb.GetBillboardResponse
	(*GetBillboardsRequest)(nil),  // 2: pb.GetBillboardsRequest
	(*GetBillboardsResponse)(nil), // 3: pb.GetBillboardsResponse
	(*Billboard)(nil),             // 4: pb.Billboard
}
var file_rpc_get_billboard_proto_depIdxs = []int32{
	4, // 0: pb.GetBillboardResponse.billboard:type_name -> pb.Billboard
	4, // 1: pb.GetBillboardsResponse.billboards:type_name -> pb.Billboard
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_rpc_get_billboard_proto_init() }
func file_rpc_get_billboard_proto_init() {
	if File_rpc_get_billboard_proto != nil {
		return
	}
	file_billboard_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_rpc_get_billboard_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBillboardRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_get_billboard_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBillboardResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_get_billboard_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBillboardsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_get_billboard_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBillboardsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_get_billboard_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_get_billboard_proto_goTypes,
		DependencyIndexes: file_rpc_get_billboard_proto_depIdxs,
		MessageInfos:      file_rpc_get_billboard_proto_msgTypes,
	}.Build()
	File_rpc_get_billboard_proto = out.File
	file_rpc_get_billboard_proto_rawDesc = nil
	file_rpc_get_billboard_proto_goTypes = nil
	file_rpc_get_billboard_proto_depIdxs = nil
}
