// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.29.2
// source: soleluxury.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SoleluxuryClient is the client API for Soleluxury service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SoleluxuryClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	LoginUser(ctx context.Context, in *LoginUserRequest, opts ...grpc.CallOption) (*LoginUserResponse, error)
	CreateStore(ctx context.Context, in *CreateStoreRequest, opts ...grpc.CallOption) (*CreateStoreResponse, error)
}

type soleluxuryClient struct {
	cc grpc.ClientConnInterface
}

func NewSoleluxuryClient(cc grpc.ClientConnInterface) SoleluxuryClient {
	return &soleluxuryClient{cc}
}

func (c *soleluxuryClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, "/pb.Soleluxury/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *soleluxuryClient) LoginUser(ctx context.Context, in *LoginUserRequest, opts ...grpc.CallOption) (*LoginUserResponse, error) {
	out := new(LoginUserResponse)
	err := c.cc.Invoke(ctx, "/pb.Soleluxury/LoginUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *soleluxuryClient) CreateStore(ctx context.Context, in *CreateStoreRequest, opts ...grpc.CallOption) (*CreateStoreResponse, error) {
	out := new(CreateStoreResponse)
	err := c.cc.Invoke(ctx, "/pb.Soleluxury/CreateStore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SoleluxuryServer is the server API for Soleluxury service.
// All implementations must embed UnimplementedSoleluxuryServer
// for forward compatibility
type SoleluxuryServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	LoginUser(context.Context, *LoginUserRequest) (*LoginUserResponse, error)
	CreateStore(context.Context, *CreateStoreRequest) (*CreateStoreResponse, error)
	mustEmbedUnimplementedSoleluxuryServer()
}

// UnimplementedSoleluxuryServer must be embedded to have forward compatible implementations.
type UnimplementedSoleluxuryServer struct {
}

func (UnimplementedSoleluxuryServer) CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedSoleluxuryServer) LoginUser(context.Context, *LoginUserRequest) (*LoginUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginUser not implemented")
}
func (UnimplementedSoleluxuryServer) CreateStore(context.Context, *CreateStoreRequest) (*CreateStoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateStore not implemented")
}
func (UnimplementedSoleluxuryServer) mustEmbedUnimplementedSoleluxuryServer() {}

// UnsafeSoleluxuryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SoleluxuryServer will
// result in compilation errors.
type UnsafeSoleluxuryServer interface {
	mustEmbedUnimplementedSoleluxuryServer()
}

func RegisterSoleluxuryServer(s grpc.ServiceRegistrar, srv SoleluxuryServer) {
	s.RegisterService(&Soleluxury_ServiceDesc, srv)
}

func _Soleluxury_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SoleluxuryServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Soleluxury/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SoleluxuryServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Soleluxury_LoginUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SoleluxuryServer).LoginUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Soleluxury/LoginUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SoleluxuryServer).LoginUser(ctx, req.(*LoginUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Soleluxury_CreateStore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateStoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SoleluxuryServer).CreateStore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Soleluxury/CreateStore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SoleluxuryServer).CreateStore(ctx, req.(*CreateStoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Soleluxury_ServiceDesc is the grpc.ServiceDesc for Soleluxury service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Soleluxury_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Soleluxury",
	HandlerType: (*SoleluxuryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _Soleluxury_CreateUser_Handler,
		},
		{
			MethodName: "LoginUser",
			Handler:    _Soleluxury_LoginUser_Handler,
		},
		{
			MethodName: "CreateStore",
			Handler:    _Soleluxury_CreateStore_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "soleluxury.proto",
}
