// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.29.2
// source: soleluxury.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SoleluxuryClient is the client API for Soleluxury service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SoleluxuryClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	LoginUser(ctx context.Context, in *LoginUserRequest, opts ...grpc.CallOption) (*LoginUserResponse, error)
	LogoutUser(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*LogoutResponse, error)
	CreateStore(ctx context.Context, in *CreateStoreRequest, opts ...grpc.CallOption) (*CreateStoreResponse, error)
	GetStore(ctx context.Context, in *GetStoreRequest, opts ...grpc.CallOption) (*GetStoreResponse, error)
	GetFirstStore(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetStoreResponse, error)
	GetStores(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetStoresResponse, error)
	UpdateStore(ctx context.Context, in *UpdateStoreRequest, opts ...grpc.CallOption) (*UpdateStoreResponse, error)
	DeleteStore(ctx context.Context, in *DeleteStoreRequest, opts ...grpc.CallOption) (*DeleteStoreResponse, error)
	CreateBillboard(ctx context.Context, in *CreateBillboardRequest, opts ...grpc.CallOption) (*CreateBillboardResponse, error)
	GetBillboard(ctx context.Context, in *GetBillboardRequest, opts ...grpc.CallOption) (*GetBillboardResponse, error)
	GetBillboards(ctx context.Context, in *GetBillboardsRequest, opts ...grpc.CallOption) (*GetBillboardsResponse, error)
	UpdateBillboard(ctx context.Context, in *UpdateBillboardRequest, opts ...grpc.CallOption) (*UpdateBillboardResponse, error)
	DeleteBillboard(ctx context.Context, in *DeleteBillboardRequest, opts ...grpc.CallOption) (*DeleteBillboardResponse, error)
	GetCategory(ctx context.Context, in *GetCategoryRequest, opts ...grpc.CallOption) (*GetCategoryResponse, error)
}

type soleluxuryClient struct {
	cc grpc.ClientConnInterface
}

func NewSoleluxuryClient(cc grpc.ClientConnInterface) SoleluxuryClient {
	return &soleluxuryClient{cc}
}

func (c *soleluxuryClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, "/pb.Soleluxury/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *soleluxuryClient) LoginUser(ctx context.Context, in *LoginUserRequest, opts ...grpc.CallOption) (*LoginUserResponse, error) {
	out := new(LoginUserResponse)
	err := c.cc.Invoke(ctx, "/pb.Soleluxury/LoginUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *soleluxuryClient) LogoutUser(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*LogoutResponse, error) {
	out := new(LogoutResponse)
	err := c.cc.Invoke(ctx, "/pb.Soleluxury/LogoutUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *soleluxuryClient) CreateStore(ctx context.Context, in *CreateStoreRequest, opts ...grpc.CallOption) (*CreateStoreResponse, error) {
	out := new(CreateStoreResponse)
	err := c.cc.Invoke(ctx, "/pb.Soleluxury/CreateStore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *soleluxuryClient) GetStore(ctx context.Context, in *GetStoreRequest, opts ...grpc.CallOption) (*GetStoreResponse, error) {
	out := new(GetStoreResponse)
	err := c.cc.Invoke(ctx, "/pb.Soleluxury/GetStore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *soleluxuryClient) GetFirstStore(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetStoreResponse, error) {
	out := new(GetStoreResponse)
	err := c.cc.Invoke(ctx, "/pb.Soleluxury/GetFirstStore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *soleluxuryClient) GetStores(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetStoresResponse, error) {
	out := new(GetStoresResponse)
	err := c.cc.Invoke(ctx, "/pb.Soleluxury/GetStores", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *soleluxuryClient) UpdateStore(ctx context.Context, in *UpdateStoreRequest, opts ...grpc.CallOption) (*UpdateStoreResponse, error) {
	out := new(UpdateStoreResponse)
	err := c.cc.Invoke(ctx, "/pb.Soleluxury/UpdateStore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *soleluxuryClient) DeleteStore(ctx context.Context, in *DeleteStoreRequest, opts ...grpc.CallOption) (*DeleteStoreResponse, error) {
	out := new(DeleteStoreResponse)
	err := c.cc.Invoke(ctx, "/pb.Soleluxury/DeleteStore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *soleluxuryClient) CreateBillboard(ctx context.Context, in *CreateBillboardRequest, opts ...grpc.CallOption) (*CreateBillboardResponse, error) {
	out := new(CreateBillboardResponse)
	err := c.cc.Invoke(ctx, "/pb.Soleluxury/CreateBillboard", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *soleluxuryClient) GetBillboard(ctx context.Context, in *GetBillboardRequest, opts ...grpc.CallOption) (*GetBillboardResponse, error) {
	out := new(GetBillboardResponse)
	err := c.cc.Invoke(ctx, "/pb.Soleluxury/GetBillboard", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *soleluxuryClient) GetBillboards(ctx context.Context, in *GetBillboardsRequest, opts ...grpc.CallOption) (*GetBillboardsResponse, error) {
	out := new(GetBillboardsResponse)
	err := c.cc.Invoke(ctx, "/pb.Soleluxury/GetBillboards", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *soleluxuryClient) UpdateBillboard(ctx context.Context, in *UpdateBillboardRequest, opts ...grpc.CallOption) (*UpdateBillboardResponse, error) {
	out := new(UpdateBillboardResponse)
	err := c.cc.Invoke(ctx, "/pb.Soleluxury/UpdateBillboard", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *soleluxuryClient) DeleteBillboard(ctx context.Context, in *DeleteBillboardRequest, opts ...grpc.CallOption) (*DeleteBillboardResponse, error) {
	out := new(DeleteBillboardResponse)
	err := c.cc.Invoke(ctx, "/pb.Soleluxury/DeleteBillboard", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *soleluxuryClient) GetCategory(ctx context.Context, in *GetCategoryRequest, opts ...grpc.CallOption) (*GetCategoryResponse, error) {
	out := new(GetCategoryResponse)
	err := c.cc.Invoke(ctx, "/pb.Soleluxury/GetCategory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SoleluxuryServer is the server API for Soleluxury service.
// All implementations must embed UnimplementedSoleluxuryServer
// for forward compatibility
type SoleluxuryServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	LoginUser(context.Context, *LoginUserRequest) (*LoginUserResponse, error)
	LogoutUser(context.Context, *emptypb.Empty) (*LogoutResponse, error)
	CreateStore(context.Context, *CreateStoreRequest) (*CreateStoreResponse, error)
	GetStore(context.Context, *GetStoreRequest) (*GetStoreResponse, error)
	GetFirstStore(context.Context, *emptypb.Empty) (*GetStoreResponse, error)
	GetStores(context.Context, *emptypb.Empty) (*GetStoresResponse, error)
	UpdateStore(context.Context, *UpdateStoreRequest) (*UpdateStoreResponse, error)
	DeleteStore(context.Context, *DeleteStoreRequest) (*DeleteStoreResponse, error)
	CreateBillboard(context.Context, *CreateBillboardRequest) (*CreateBillboardResponse, error)
	GetBillboard(context.Context, *GetBillboardRequest) (*GetBillboardResponse, error)
	GetBillboards(context.Context, *GetBillboardsRequest) (*GetBillboardsResponse, error)
	UpdateBillboard(context.Context, *UpdateBillboardRequest) (*UpdateBillboardResponse, error)
	DeleteBillboard(context.Context, *DeleteBillboardRequest) (*DeleteBillboardResponse, error)
	GetCategory(context.Context, *GetCategoryRequest) (*GetCategoryResponse, error)
	mustEmbedUnimplementedSoleluxuryServer()
}

// UnimplementedSoleluxuryServer must be embedded to have forward compatible implementations.
type UnimplementedSoleluxuryServer struct {
}

func (UnimplementedSoleluxuryServer) CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedSoleluxuryServer) LoginUser(context.Context, *LoginUserRequest) (*LoginUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginUser not implemented")
}
func (UnimplementedSoleluxuryServer) LogoutUser(context.Context, *emptypb.Empty) (*LogoutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LogoutUser not implemented")
}
func (UnimplementedSoleluxuryServer) CreateStore(context.Context, *CreateStoreRequest) (*CreateStoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateStore not implemented")
}
func (UnimplementedSoleluxuryServer) GetStore(context.Context, *GetStoreRequest) (*GetStoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStore not implemented")
}
func (UnimplementedSoleluxuryServer) GetFirstStore(context.Context, *emptypb.Empty) (*GetStoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFirstStore not implemented")
}
func (UnimplementedSoleluxuryServer) GetStores(context.Context, *emptypb.Empty) (*GetStoresResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStores not implemented")
}
func (UnimplementedSoleluxuryServer) UpdateStore(context.Context, *UpdateStoreRequest) (*UpdateStoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateStore not implemented")
}
func (UnimplementedSoleluxuryServer) DeleteStore(context.Context, *DeleteStoreRequest) (*DeleteStoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteStore not implemented")
}
func (UnimplementedSoleluxuryServer) CreateBillboard(context.Context, *CreateBillboardRequest) (*CreateBillboardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBillboard not implemented")
}
func (UnimplementedSoleluxuryServer) GetBillboard(context.Context, *GetBillboardRequest) (*GetBillboardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBillboard not implemented")
}
func (UnimplementedSoleluxuryServer) GetBillboards(context.Context, *GetBillboardsRequest) (*GetBillboardsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBillboards not implemented")
}
func (UnimplementedSoleluxuryServer) UpdateBillboard(context.Context, *UpdateBillboardRequest) (*UpdateBillboardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBillboard not implemented")
}
func (UnimplementedSoleluxuryServer) DeleteBillboard(context.Context, *DeleteBillboardRequest) (*DeleteBillboardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBillboard not implemented")
}
func (UnimplementedSoleluxuryServer) GetCategory(context.Context, *GetCategoryRequest) (*GetCategoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCategory not implemented")
}
func (UnimplementedSoleluxuryServer) mustEmbedUnimplementedSoleluxuryServer() {}

// UnsafeSoleluxuryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SoleluxuryServer will
// result in compilation errors.
type UnsafeSoleluxuryServer interface {
	mustEmbedUnimplementedSoleluxuryServer()
}

func RegisterSoleluxuryServer(s grpc.ServiceRegistrar, srv SoleluxuryServer) {
	s.RegisterService(&Soleluxury_ServiceDesc, srv)
}

func _Soleluxury_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SoleluxuryServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Soleluxury/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SoleluxuryServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Soleluxury_LoginUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SoleluxuryServer).LoginUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Soleluxury/LoginUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SoleluxuryServer).LoginUser(ctx, req.(*LoginUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Soleluxury_LogoutUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SoleluxuryServer).LogoutUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Soleluxury/LogoutUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SoleluxuryServer).LogoutUser(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Soleluxury_CreateStore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateStoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SoleluxuryServer).CreateStore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Soleluxury/CreateStore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SoleluxuryServer).CreateStore(ctx, req.(*CreateStoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Soleluxury_GetStore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SoleluxuryServer).GetStore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Soleluxury/GetStore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SoleluxuryServer).GetStore(ctx, req.(*GetStoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Soleluxury_GetFirstStore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SoleluxuryServer).GetFirstStore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Soleluxury/GetFirstStore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SoleluxuryServer).GetFirstStore(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Soleluxury_GetStores_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SoleluxuryServer).GetStores(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Soleluxury/GetStores",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SoleluxuryServer).GetStores(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Soleluxury_UpdateStore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SoleluxuryServer).UpdateStore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Soleluxury/UpdateStore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SoleluxuryServer).UpdateStore(ctx, req.(*UpdateStoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Soleluxury_DeleteStore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteStoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SoleluxuryServer).DeleteStore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Soleluxury/DeleteStore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SoleluxuryServer).DeleteStore(ctx, req.(*DeleteStoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Soleluxury_CreateBillboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBillboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SoleluxuryServer).CreateBillboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Soleluxury/CreateBillboard",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SoleluxuryServer).CreateBillboard(ctx, req.(*CreateBillboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Soleluxury_GetBillboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBillboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SoleluxuryServer).GetBillboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Soleluxury/GetBillboard",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SoleluxuryServer).GetBillboard(ctx, req.(*GetBillboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Soleluxury_GetBillboards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBillboardsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SoleluxuryServer).GetBillboards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Soleluxury/GetBillboards",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SoleluxuryServer).GetBillboards(ctx, req.(*GetBillboardsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Soleluxury_UpdateBillboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBillboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SoleluxuryServer).UpdateBillboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Soleluxury/UpdateBillboard",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SoleluxuryServer).UpdateBillboard(ctx, req.(*UpdateBillboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Soleluxury_DeleteBillboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBillboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SoleluxuryServer).DeleteBillboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Soleluxury/DeleteBillboard",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SoleluxuryServer).DeleteBillboard(ctx, req.(*DeleteBillboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Soleluxury_GetCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SoleluxuryServer).GetCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Soleluxury/GetCategory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SoleluxuryServer).GetCategory(ctx, req.(*GetCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Soleluxury_ServiceDesc is the grpc.ServiceDesc for Soleluxury service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Soleluxury_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Soleluxury",
	HandlerType: (*SoleluxuryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _Soleluxury_CreateUser_Handler,
		},
		{
			MethodName: "LoginUser",
			Handler:    _Soleluxury_LoginUser_Handler,
		},
		{
			MethodName: "LogoutUser",
			Handler:    _Soleluxury_LogoutUser_Handler,
		},
		{
			MethodName: "CreateStore",
			Handler:    _Soleluxury_CreateStore_Handler,
		},
		{
			MethodName: "GetStore",
			Handler:    _Soleluxury_GetStore_Handler,
		},
		{
			MethodName: "GetFirstStore",
			Handler:    _Soleluxury_GetFirstStore_Handler,
		},
		{
			MethodName: "GetStores",
			Handler:    _Soleluxury_GetStores_Handler,
		},
		{
			MethodName: "UpdateStore",
			Handler:    _Soleluxury_UpdateStore_Handler,
		},
		{
			MethodName: "DeleteStore",
			Handler:    _Soleluxury_DeleteStore_Handler,
		},
		{
			MethodName: "CreateBillboard",
			Handler:    _Soleluxury_CreateBillboard_Handler,
		},
		{
			MethodName: "GetBillboard",
			Handler:    _Soleluxury_GetBillboard_Handler,
		},
		{
			MethodName: "GetBillboards",
			Handler:    _Soleluxury_GetBillboards_Handler,
		},
		{
			MethodName: "UpdateBillboard",
			Handler:    _Soleluxury_UpdateBillboard_Handler,
		},
		{
			MethodName: "DeleteBillboard",
			Handler:    _Soleluxury_DeleteBillboard_Handler,
		},
		{
			MethodName: "GetCategory",
			Handler:    _Soleluxury_GetCategory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "soleluxury.proto",
}
